name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: '${{ matrix.java }}'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the Jar
        run: './gradlew clean test build'
